import type { Metadata } from "next";
// import { dir } from 'i18next';
// import configI18next from 'root/next-i18next.config';
// import { Geist, Geist_Mono } from "next/font/google";
import "@/assets/css/globals.css";
import '@fontsource/roboto/100.css';
import '@fontsource/roboto/200.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/600.css';
import '@fontsource/roboto/700.css';
import '@fontsource/roboto/800.css';
import { Box, Toolbar } from "@mui/material";
import TranslationProvider from "@/presentation/language/components/TranslationProvider";
import CssBaseline, { ThemeProvider, customTheme } from '@/presentation/theme/components';
import {
    NavbarWithDrawer,
    Footer
    // CustomSpeedDial
} from "@/presentation/shared/components";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Homero Celano",
    description: "Generated by create next app"
};

// export async function generateStaticParams() {
//     return configI18next.i18n.locales.map(lng => ({ lng }));
// };

export default function RootLayout({
    children
    // params: { lng }
}: Readonly<{
    children: React.ReactNode;
    // params: { lng: string };
}>) {
    return (
        <ThemeProvider theme={customTheme}>
            <CssBaseline />
            <html
                lang={'es'}
            // lang={lng}
            // dir={dir(lng)}
            >
                <head>
                    <link rel="icon" href="/img/favicon.ico" />
                </head>
                <body
                // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <TranslationProvider>
                        <Box
                            sx={{
                                // minHeight: '100vh',
                                minHeight: '100dvh',
                                display: 'flex',
                                flexDirection: 'column'
                            }}
                        >
                            <header>
                                <NavbarWithDrawer />
                                <Toolbar />
                            </header>
                            {/* <main> */}
                            {/* <div id="main"> */}
                            <Box
                                component="main"
                                sx={{
                                    flex: 1,
                                    py: 3,
                                    px: { xs: 2, sm: 4, md: 6, lg: 8 }
                                }}
                            >
                                {children}
                            </Box>
                            {/* </div> */}
                            {/* </main> */}
                            <Footer />
                            {/* <CustomSpeedDial /> */}
                        </Box>
                    </TranslationProvider>
                </body>
            </html>
        </ThemeProvider >
    );
};
